[window]
padding = { x = 5, y = 5 }
decorations = "none"
dynamic_padding = false

[font]
normal = { family = "Monospace", style = "Regular" }
size = 10.0

[colors.primary]
background = "#0d1117"  # fond très sombre
foreground = "#c9d1d9"  # gris clair (lune/étoiles)

[colors.normal]
black   = "#0d1117"
red     = "#d95468"   # léger rouge (contraste)
green   = "#8bd49c"   # vert doux
yellow  = "#ebd28c"   # jaune pâle
blue    = "#7aa2f7"   # bleu étoilé
magenta = "#c678dd"   # violet doux
cyan    = "#7fcfff"   # cyan lunaire
white   = "#dcdcdc"

[colors.bright]
black   = "#161b22"
red     = "#ff6b81"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#d0aaff"
cyan    = "#9be2f2"
white   = "#ffffff"

[colors.selection]
text = "#0d1117"
background = "#7aa2f7"

[cursor]
style = "Block"
unfocused_hollow = true

