# Import des couleurs
import = ["~/.config/alacritty/themix-colors.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "none"
dynamic_padding = false

[font]
normal = { family = "Monospace", style = "Regular" }
size = 10.0

[cursor]
style = "Block"
unfocused_hollow = true
