
[window]
padding = { x = 5, y = 5 }
decorations = "none"
dynamic_padding = false

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12.0

[cursor]
style = "Block"
unfocused_hollow = true

[general]
# Import des couleurs
import = ["/home/lazarobradovic/.config/alacritty/themix-colors.toml"]
